Import Corpus

In [1]:
text = open('ExtractedText.txt', encoding='utf-8').read()
print(text[:500]) #Print the first 500 letters

ਕੁੱਝ ਵਿਦਵਾਨਾਂ ਲਈ ਤਾਂ ‘ਕਹਾਣੀ ਸਹਿਜ ਸਾਧਾਰਣ ਸੱਚ ਨੂੰ ਸਰਲ ਸਪਾਟ ਰੂਪ ਵਿਚ ਕਹਿੰਦੀ ਹੈ’ ਅਤੇ ‘ਏਸ ਕਲਾ ਨੂੰ... ਕਿਸੇ ਗੁੰਝਲਦਾਰ ਸਾਹਿਤ ਸ਼ਾਸਤਰ ਦੀ ਮੁਹਤਾਜ਼ੀ ਨਹੀਂ ।’ ਪਰ ਸਹਿਜ ਸਾਧਾਰਣ ਸੱਚ ਨੂੰ ਨਾ ਕਹਾਣੀ ਸਰਲ ਸਪਾਟ ਰੂਪ ਵਿਚ ਪੇਸ਼ ਕਰਦੀ ਹੈ ਅਤੇ ਨਾ ਹੀ ਇਸ ਦਾ ਸਾਹਿਤ ਸ਼ਾਸਤਰ ਏਨਾ ਸਰਲ ਰਹੇਗਾ । ਜਿਸ ਤਰ੍ਹਾਂ ਕਵਿਤਾ ਕੇਵਲ ਛੰਦ ਪ੍ਰਬੰਧ ਨਹੀਂ ਹੁੰਦੀ, ਇਸੇ ਤਰ੍ਹਾਂ ਕਹਾਣੀ ਕੇਵਲ ਕਹਾਣੀ (ਕਥਾ) ਨਹੀਂ ਹੁੰਦੀ । ਕਹਾਣੀ ਦੀ ਗੱਲ ਜਦੋਂ ਅਸੀਂ ਇਕ ਰੂਪਾਕਾਰ ਦੇ ਦ੍ਰਿਸ਼ਟੀਕੋਣ ਤੋਂ ਕਰਦੇ ਹਾਂ ਤਾਂ ਇਹ ਵੀ ਕਥਾ ਦੇ ਪਰੰਪਰਾਈ ਰੂਪ ਨੂੰ ਤਜ ਕੇ ਨਵੀਆਂ ਸੰਭਾਵਨਾਵਾਂ ਨਾਲ ਜਾ ਜੁੜਦੀ ਹੈ ।
ਬਿਰਤਾਂਤ ਦੀ ਬਿਰਤੀ ਵਧੇਰੇ ਕਰਕੇ 


Split corpus into sentences

In [2]:
import re
sentenceEnd = ['|', '।']
pattern = f"[{''.join(re.escape(ch) for ch in sentenceEnd)}]"
corpus = re.split(pattern, text)
corpus = [s.strip() for s in corpus if s.strip()]
print("Total sentences:", len(corpus))
print(corpus[:3])

Total sentences: 5786
['ਕੁੱਝ ਵਿਦਵਾਨਾਂ ਲਈ ਤਾਂ ‘ਕਹਾਣੀ ਸਹਿਜ ਸਾਧਾਰਣ ਸੱਚ ਨੂੰ ਸਰਲ ਸਪਾਟ ਰੂਪ ਵਿਚ ਕਹਿੰਦੀ ਹੈ’ ਅਤੇ ‘ਏਸ ਕਲਾ ਨੂੰ... ਕਿਸੇ ਗੁੰਝਲਦਾਰ ਸਾਹਿਤ ਸ਼ਾਸਤਰ ਦੀ ਮੁਹਤਾਜ਼ੀ ਨਹੀਂ', '’ ਪਰ ਸਹਿਜ ਸਾਧਾਰਣ ਸੱਚ ਨੂੰ ਨਾ ਕਹਾਣੀ ਸਰਲ ਸਪਾਟ ਰੂਪ ਵਿਚ ਪੇਸ਼ ਕਰਦੀ ਹੈ ਅਤੇ ਨਾ ਹੀ ਇਸ ਦਾ ਸਾਹਿਤ ਸ਼ਾਸਤਰ ਏਨਾ ਸਰਲ ਰਹੇਗਾ', 'ਜਿਸ ਤਰ੍ਹਾਂ ਕਵਿਤਾ ਕੇਵਲ ਛੰਦ ਪ੍ਰਬੰਧ ਨਹੀਂ ਹੁੰਦੀ, ਇਸੇ ਤਰ੍ਹਾਂ ਕਹਾਣੀ ਕੇਵਲ ਕਹਾਣੀ (ਕਥਾ) ਨਹੀਂ ਹੁੰਦੀ']


Clean up

In [3]:
import string
punctuations = string.punctuation + '।' + '\n' + '‘’'
def cleanSentence(sentence):
    return sentence.translate(str.maketrans('', '', punctuations))

cleanedSentences = [cleanSentence(s) for s in corpus]
print(cleanedSentences[:3])

['ਕੁੱਝ ਵਿਦਵਾਨਾਂ ਲਈ ਤਾਂ ਕਹਾਣੀ ਸਹਿਜ ਸਾਧਾਰਣ ਸੱਚ ਨੂੰ ਸਰਲ ਸਪਾਟ ਰੂਪ ਵਿਚ ਕਹਿੰਦੀ ਹੈ ਅਤੇ ਏਸ ਕਲਾ ਨੂੰ ਕਿਸੇ ਗੁੰਝਲਦਾਰ ਸਾਹਿਤ ਸ਼ਾਸਤਰ ਦੀ ਮੁਹਤਾਜ਼ੀ ਨਹੀਂ', ' ਪਰ ਸਹਿਜ ਸਾਧਾਰਣ ਸੱਚ ਨੂੰ ਨਾ ਕਹਾਣੀ ਸਰਲ ਸਪਾਟ ਰੂਪ ਵਿਚ ਪੇਸ਼ ਕਰਦੀ ਹੈ ਅਤੇ ਨਾ ਹੀ ਇਸ ਦਾ ਸਾਹਿਤ ਸ਼ਾਸਤਰ ਏਨਾ ਸਰਲ ਰਹੇਗਾ', 'ਜਿਸ ਤਰ੍ਹਾਂ ਕਵਿਤਾ ਕੇਵਲ ਛੰਦ ਪ੍ਰਬੰਧ ਨਹੀਂ ਹੁੰਦੀ ਇਸੇ ਤਰ੍ਹਾਂ ਕਹਾਣੀ ਕੇਵਲ ਕਹਾਣੀ ਕਥਾ ਨਹੀਂ ਹੁੰਦੀ']


Import Stopwords, tokenise sentences and remove stopwords from corpus

In [6]:
with open('Stopwords.txt', 'r', encoding='utf-8') as f:
    stopWords = [word.strip('"') for word in f.read().split(',')]

from indicnlp.tokenize import indic_tokenize

sentencesWithoutStopwords = []
for sentence in cleanedSentences:
    tokens = indic_tokenize.trivial_tokenize(sentence)
    filteredTokens = [token for token in tokens if token not in stopWords]
    sentencesWithoutStopwords.append(filteredTokens)

print(sentencesWithoutStopwords[:3])


[['ਕੁੱਝ', 'ਵਿਦਵਾਨਾਂ', 'ਕਹਾਣੀ', 'ਸਹਿਜ', 'ਸਾਧਾਰਣ', 'ਸੱਚ', 'ਸਰਲ', 'ਸਪਾਟ', 'ਰੂਪ', 'ਵਿਚ', 'ਕਹਿੰਦੀ', 'ਕਲਾ', 'ਕਿਸੇ', 'ਗੁੰਝਲਦਾਰ', 'ਸਾਹਿਤ', 'ਸ਼ਾਸਤਰ', 'ਦੀ', 'ਮੁਹਤਾਜ਼ੀ', 'ਨਹੀਂ'], ['ਸਹਿਜ', 'ਸਾਧਾਰਣ', 'ਸੱਚ', 'ਨਾ', 'ਕਹਾਣੀ', 'ਸਰਲ', 'ਸਪਾਟ', 'ਰੂਪ', 'ਵਿਚ', 'ਪੇਸ਼', 'ਕਰਦੀ', 'ਨਾ', 'ਇਸ', 'ਸਾਹਿਤ', 'ਸ਼ਾਸਤਰ', 'ਏਨਾ', 'ਸਰਲ', 'ਰਹੇਗਾ'], ['ਜਿਸ', 'ਤਰ੍ਹਾਂ', 'ਕਵਿਤਾ', 'ਕੇਵਲ', 'ਛੰਦ', 'ਪ੍ਰਬੰਧ', 'ਨਹੀਂ', 'ਹੁੰਦੀ', 'ਇਸੇ', 'ਤਰ੍ਹਾਂ', 'ਕਹਾਣੀ', 'ਕੇਵਲ', 'ਕਹਾਣੀ', 'ਕਥਾ', 'ਨਹੀਂ', 'ਹੁੰਦੀ']]


Import Lexicon

In [7]:
import pandas as pd

emotions = ['anger', 'anticipation', 'disgust', 'fear', 'joy',
            'negative', 'positive', 'sadness', 'surprise', 'trust']

lexiconDf = pd.read_csv('Punjabi-NRC-EmoLex.txt', sep='\t', encoding='utf-8')

#Filter out rows that are 0 for all emotions
lexiconFiltered = lexiconDf[lexiconDf[emotions].sum(axis=1) > 0]
lexiconFiltered = lexiconFiltered.reset_index(drop=True)

print(lexiconFiltered.head())


  English Word  anger  anticipation  disgust  fear  joy  negative  positive  \
0       abacus      0             0        0     0    0         0         0   
1      abandon      0             0        0     1    0         1         0   
2    abandoned      1             0        0     1    0         1         0   
3  abandonment      1             0        0     1    0         1         0   
4         abba      0             0        0     0    0         0         1   

   sadness  surprise  trust Punjabi Word  
0        0         0      1       abacus  
1        1         0      0     ਛੱਡ ਦੇਣਾ  
2        1         0      0    ਛੱਡ ਦਿੱਤਾ  
3        1         1      0         ਤਿਆਗ  
4        0         0      0         ਅੱਬਾ  


In [8]:
from collections import defaultdict

emotionLexicon = defaultdict(list)
for _, row in lexiconDf.iterrows():
    punjabi_word = str(row['Punjabi Word']).strip()
    for emotion in emotions:
        if row[emotion] == 1:
            emotionLexicon[punjabi_word].append(emotion)

#Test to see if everything is loaded correctly
print(emotionLexicon['ਛੱਡ ਦੇਣਾ'])

['fear', 'negative', 'sadness']


Generate features and generate labels through the lexicon per sentence

In [9]:
import numpy as np
from collections import Counter
def autoLabel(tokens, lexicon):
    emoCounts = Counter()
    for token in tokens:
        for em in lexicon.get(token, []):
            emoCounts[em] = emoCounts[em] + 1
    if not emoCounts:
        return 'neutral'
    return emoCounts.most_common(1)[0][0]

def getEmotionVector(tokens):
    counts = Counter()
    for token in tokens:
        for em in emotionLexicon.get(token, []):
            counts[em] += 1
    return np.array([counts.get(em, 0) for em in emotions])

# Features and labels
xFeatures = np.array([getEmotionVector(tokens) for tokens in sentencesWithoutStopwords])
yLabels = [autoLabel(tokens, emotionLexicon) for tokens in sentencesWithoutStopwords]


Encode Labels

In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
yEncoded = le.fit_transform(yLabels)

Test

In [11]:
print("xFeatures shape:", xFeatures.shape)
print("yEncoded shape:", yEncoded.shape)

xFeatures shape: (5786, 10)
yEncoded shape: (5786,)


Split data into training and validation sets

In [12]:
from sklearn.model_selection import train_test_split
xTrain, xPred, yTrain, yPred = train_test_split(xFeatures, yEncoded, test_size=0.2, random_state=42)

Build and train model

In [13]:
import tensorflow as tf
from tensorflow.keras import layers, models

model = models.Sequential([
    layers.Input(shape=(len(emotions),)),
    layers.Dense(16, activation='relu'),
    layers.Dense(8, activation='relu'),
    layers.Dense(len(set(yEncoded)), activation='softmax')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(xTrain, yTrain, epochs=10, batch_size=16)


Epoch 1/10
290/290 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.2933 - loss: 2.1703
Epoch 2/10
290/290 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7746 - loss: 1.3901
Epoch 3/10
290/290 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7814 - loss: 0.9600
Epoch 4/10
290/290 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7916 - loss: 0.7103
Epoch 5/10
290/290 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8246 - loss: 0.5638
Epoch 6/10
290/290 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8369 - loss: 0.5043
Epoch 7/10
290/290 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8457 - loss: 0.4592
Epoch 8/10
290/290 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8430 - loss: 0.4103
Epoch 9/10
290/290 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8678 - loss: 0.3761
Epoch 10/10
290/290 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8832 - loss: 0.3499


Test prediction

In [14]:
sample = "ਮੈਂ ਬਹੁਤ ਖੁਸ਼ ਹਾਂ"
tokens = indic_tokenize.trivial_tokenize(sample)
features = getEmotionVector(tokens).reshape(1, -1)
pred_class = model.predict(features).argmax(axis=1)
print("Predicted:", le.inverse_transform(pred_class))


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step
Predicted: ['positive']


In [15]:
from sklearn.metrics import confusion_matrix
yPred = model.predict(xPred).argmax(axis=1)
cm = confusion_matrix(yPred, yPred)
print(cm)

37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step 
[[ 33   0   0   0   0   0   0   0   0   0]
 [  0  82   0   0   0   0   0   0   0   0]
 [  0   0  17   0   0   0   0   0   0   0]
 [  0   0   0  30   0   0   0   0   0   0]
 [  0   0   0   0  22   0   0   0   0   0]
 [  0   0   0   0   0 227   0   0   0   0]
 [  0   0   0   0   0   0 344   0   0   0]
 [  0   0   0   0   0   0   0 360   0   0]
 [  0   0   0   0   0   0   0   0   1   0]
 [  0   0   0   0   0   0   0   0   0  42]]
